apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/antcosta-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus@sha256:7b9f1a1bd78295c5d1968a06f6e95334a00029e231d97918fb1de588a7f3f22e
        name: my-java-quarkus
        resources: {}
status: {}
